channels: 
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - nextflow
  - fastqc
  - fastp
  - bwa
  - samtools
  - gatk4
  - snpeff
  - plink
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pip
  - tabix
  - wget